### ISSUE TITLE
No issue, but would love to see additional geoms

### ISSUE THREAD

**Issue by davisj2007** [marcmenem/ggshadow#1]
Love this package, particularly since a plotting style I use is very "retro" heavy.  i tried to back into a geom_point replicating your overall glow aesthetic, but can't figure it out.  What would it take to produce a geom_point, geom_bar, etc version?

Thanks again, love the work

**Comment by marcmenem** [comment]
Thank you for the compliment.

I have only used geom_shadowline and geom_shadowpoint for "real life" work, I added the glow as a fun experiment, happy to see that someone found it useful, and I would love to see example charts using it. 

Here is where I got te inspiration: https://matplotlib.org/matplotblog/posts/matplotlib-cyberpunk-style/
 
It wouldn't take a lot of effort to build a glowpoint. I will look into it when I have some free time.

I am not sure what you are trying to achieve with geom_bar, do you have example charts of what you have in mind? I haven't looked into the internal of ggplot for other geoms.

**Comment by davisj2007** [comment]
I also use geom_shadowline more for "real" life (I got tired of building hacking my own version and I'm not a very good developer, which led me to you) but love "glow" for my personal work.  I use a very "neon"-esque plotting theme, and the glow geoms really make it pop (https://twitter.com/davisj2007/status/1344667510566744065?s=20)

I have no specific examples of additional geoms I'd be interested in, outside of keeping my private work as 80s cyberpunk as possible 👍 
Thanks again!

**Comment by davisj2007** [comment]
![image](https://user-images.githubusercontent.com/7129791/103704591-8a9a4280-4f77-11eb-8853-639ee392d007.png)

**Comment by marcmenem** [comment]
Just added geom_glowpoint. I am thinking of adding a shaded area below lines and glowing lolipops and dumbbell should be easy as well.

**Comment by davisj2007** [comment]
This is great!  Exactly what I was looking for and love.  Thanks again for quick response and keep up the work (btw, we're transitioning from my hacky shadowlines to your much easier to implement version :) )

**Comment by marcmenem** [comment]
Hi Jake, happy to hear this is useful, your comment was the impulse I needed to put in the effort to submit to CRAN. I will wait for more feedback before adding new geoms.
