### ISSUE TITLE
Adding support for `linewidth` parameter to `ggshadow::geom_shadowline()` and other functions

### ISSUE THREAD

**Issue by elipousson** [marcmenem/ggshadow#6]
It would be great to update the package to add support for `linewidth` parameter to `ggshadow::geom_shadowline()` and other functions. This [blog post provides fairly detailed guidance](https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/) so I'd be happy to open a pull request if you're interested in seeing this update to the package.

**Comment by marcmenem** [comment]
Hi Eli, 
It is great to see that this project is alive and have users. I am definitely happy to review and merge a pull request. tbh, I have not used R in a while, so would rather have someone actively using it do the update

**Comment by elipousson** [comment]
That sounds great, @marcmenem. I started on these changes yesterday evening and I think I've got it working.

Do you mind if I make add a couple other changes in the same PR? I already started adding some snapshot tests using testthat but I can also switch the README over to a Rmd format and would be glad to incorporate cli for some improved formatting on the error messages and alerts.

**Comment by elipousson** [comment]
I think this is complete so I'm going to go ahead and close the issue.
